### ISSUE TITLE
Build Opencv

### ISSUE THREAD

**Issue by NguyenVanThanhHust** [cyrusbehr/sdk_design#4]
I'm trying build OpenCV with ./build_opencv.sh
I meet this error
```
build_opencv.sh: 13: cd: can't cd to build_amd64
CMake Error at /usr/local/share/cmake-3.19/Modules/CMakeDetermineSystem.cmake:110 (message):
  Could not find toolchain file:
  ../platforms/linux/arm-gnueabi.toolchain.cmake
Call Stack (most recent call first):
  CMakeLists.txt:26 (project)


CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
build_opencv.sh: 24: cd: can't cd to build_arm32
CMake Error at /usr/local/share/cmake-3.19/Modules/CMakeDetermineSystem.cmake:110 (message):
  Could not find toolchain file:
  ../platforms/linux/arm-gnueabi.toolchain.cmake
Call Stack (most recent call first):
  CMakeLists.txt:26 (project)


CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
build_opencv.sh: 36: cd: can't cd to build_arm64
build_opencv.sh: 37: build_opencv.sh: ../platforms/linux/aarch64-gnu.toolchain.cmake: not found
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
```

I think the error come from this line
`
cmake -DCMAKE_TOOLCHAIN_FILE="../platforms/linux/arm-gnueabi.toolchain.cmake"
`
could your provide your `platfroms` folder?

**Comment by cyrusbehr** [comment]
Hi @NguyenVanThanhHust 
So the path provided to `cmake` is relative, and it is actually referring to the `platforms` directory in the OpenCV repository, found [here](https://github.com/opencv/opencv/tree/master/platforms). However, that does not seem to be the issue.

The issue is actually related to what is printed on the first line `build_opencv.sh: 13: cd: can't cd to build_amd64`.
Since the script is unable to enter the `build_amd64` directory, then the relative path provided to `cmake` for finding the opencv toolchain file isn't working. 

Any ideas why the `cd` command wouldn't be working from your shell script? My guess is incorrect permission or something else related to the shell script. You can try executing each command in [this](https://github.com/cyrusbehr/sdk_design/blob/master/3rdparty/build_opencv.sh) script in your terminal manually and see if that works.

**Comment by NguyenVanThanhHust** [comment]
You're right. It is about permission. I fixed it with sudo to install it. Thank you.

**Comment by cyrusbehr** [comment]
Happy to help.
